# Generated by Django 3.2 on 2021-04-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=400)),
                ('poster', models.ImageField(upload_to='poster')),
            ],
        ),
    ]
