# Generated by Django 3.2 on 2021-04-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Thumbnail',
            field=models.ImageField(default=1, upload_to='poster'),
            preserve_default=False,
        ),
    ]
